    image:
      name: ghcr.io/nmfs-opensci/container-images/py-rocket-geospatial:latest
      tag: 6ee57a9
      pullPolicy: Always
    profileList:
      - display_name: "Select image and RAM"
        description: &profile_list_description "Start a container with at least a chosen share of capacity on a node of this type"
        default: true
        slug: small
        profile_options:
          image: &profile_options_image
            display_name: Image
            choices:
              python:
                display_name: Py - Openscapes Python 39dffde
                slug: python
                kubespawner_override:
                  image: openscapes/python:39dffde
              pyrbase:
                display_name: Py-R - base image 4.4-3.10
                slug: pyrbase
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/py-rocket-base:latest
              pyrgeo:
                display_name: Py-R - Base geospatial image - py-rocket-geospatial latest
                slug: pyrgeo
                default: true
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/py-rocket-geospatial:latest
              coastwatch:
                display_name: Py-R - CoastWatch - nmfs-opensci coastwatch latest
                slug: coastwatch
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/coastwatch:latest
              aomlomics:
                display_name: Py - Tourmaline Snakemake workflow for QIIME 2 v.2023.5
                slug: aomlomics
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/aomlomics-jh:latest
              iorocker:
                display_name: R - R geospatial w sdmTMB - r-geospatial-sdm latest
                slug: rgeospatialsdm
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/r-geospatial-sdm:latest
              echopype:
                display_name: Py - Echopype with pangeo nmfs-opensci echopype latest
                slug: echopype
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/echopype:latest
              arcgis:
                display_name: Py - ArcGIS Python 3.9
                slug: arcgis
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/arcgis:latest
              cboettig:
                display_name: Py-R - NASA TOPS - boettiger-lab nasa-tops latest
                slug: cboettig
                kubespawner_override:
                  image: ghcr.io/boettiger-lab/nasa-tops:latest 
              vast:
                display_name: R - VAST with TMB - nmfs-opensci vast latest
                kubespawner_override:
                  image: ghcr.io/nmfs-opensci/container-images/vast:latest
              oci:
                display_name: Py - Ocean Color with OCSSW
                kubespawner_override:
                  image: http://quay.io/pacehackweek/pace-2024:latest
