# The config file for the dask-enabled hub
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: <replace with your OAuth id>
        client_secret: <replace with your OAuth app secret>
        oauth_callback_url: https://<your url>/hub/oauth_callback
        allowed_organizations:
          - <your org>:<your team name>
        scope:
          - read:org
      JupyterHub:
        authenticator_class: github
    allowNamedServers: true
    networkPolicy:
      # FIXME: For dask gateway
      enabled: false
    readinessProbe:
      enabled: false
  scheduling:
    userScheduler:
      enabled: true
    userPods:
      nodeAffinity:
        matchNodePurpose: require
  proxy:
    https:
      enabled: true
      hosts:
        - <your url>
      letsencrypt:
        contactEmail: eli.holmes@noaa.gov        
  singleuser:
    # Defines the default image
    image:
      name: openscapes/python
      tag: f577786
    storage:
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan/shared
          subPath: _shared
          readOnly: false
    profileList:
      - display_name: "Small: up to 4 CPU / 32 GB RAM"
        description: &profile_list_description "Start a container with at least a chosen share of capacity on a node of this type"
        slug: small
        default: true
        profile_options:
          image: 
            display_name: Image
            choices:
              python:
                display_name: Python
                default: true
                slug: python
                kubespawner_override:
                  image: openscapes/python:f577786
              rocker:
                display_name: R
                slug: rocker
                kubespawner_override:
                  image: openscapes/rocker:a7596b5
          requests:
            display_name: Node share
            choices:
              mem_1:
                default: true
                display_name: ~1 GB, ~0.125 CPU
                kubespawner_override:
                  mem_guarantee: 0.904G
                  cpu_guarantee: 0.013
              mem_2:
                display_name: ~2 GB, ~0.25 CPU
                kubespawner_override:
                  mem_guarantee: 1.809G
                  cpu_guarantee: 0.025
              mem_4:
                display_name: ~4 GB, ~0.5 CPU
                kubespawner_override:
                  mem_guarantee: 3.617G
                  cpu_guarantee: 0.05
              mem_8:
                display_name: ~8 GB, ~1.0 CPU
                kubespawner_override:
                  mem_guarantee: 7.234G
                  cpu_guarantee: 0.1
              mem_16:
                display_name: ~16 GB, ~2.0 CPU
                kubespawner_override:
                  mem_guarantee: 14.469G
                  cpu_guarantee: 0.2
              mem_32:
                display_name: ~32 GB, ~4.0 CPU
                kubespawner_override:
                  mem_guarantee: 28.937G
                  cpu_guarantee: 0.4
        kubespawner_override:
          cpu_limit: null
          mem_limit: null
          node_selector:
            node.kubernetes.io/instance-type: r5.xlarge
dask-gateway:
  gateway:
    extraConfig:
      idle: |-
        # timeout after 30 minutes of inactivity
        c.KubeClusterConfig.idle_timeout = 1800        
        
