apiVersion: v1
kind: PersistentVolume
metadata:
  name: daskhub-shared
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.0.4
    path: https://daskhubnfs.file.core.windows.net/daskhub-shared