apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daskhub-shared
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  selector: 
    matchLabels:
      type: nfs