kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-custom
provisioner: kubernetes.io/Azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  kind: Managed