hub:
  config:
    GitHubOAuthenticator:
      client_id: <id when you register your OAuth on GitHub>
      client_secret: <secret when you register your OAuth on GitHub>
      oauth_callback_url: https://gcp.opensci.live/hub/oauth_callback
      allowed_organizations:
        - nmfs-opensci:DaskHub
      scope:
        - read:org
    JupyterHub:
      authenticator_class: github

proxy:
  traefik:
    extraInitContainers:
      # This startup delay can help the k8s container network find the 
      # https certificate and allow letsencrypt to work
      - name: startup-delay
        image: busybox:stable
        command: ["sh", "-c", "sleep 10"]
  https:
    enabled: true
    hosts:
      - gcp.opensci.live
    letsencrypt:
      contactEmail: eli.holmes@noaa.gov
